# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.63"

default_platform :ios

platform :ios do
	before_all do
		# ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
		ENV["IOS_BUILD_SCHEME"] = "HelloWorld"
		ENV["IOS_BUILD_WORKSPACE"] = "HelloWorld.xcworkspace"
		cocoapods
	end

	desc "Create a Release version of the app"
	lane :release_app do
		bundle_rn
		test
		test_coverage
		inc_build_number
		build_app configuration:"Release"
	end

	desc "Create a QA version of the app"
	lane :qa_app do
		bundle_rn
		test
		test_coverage
		inc_build_number
		build_app configuration:"QA"
	end

	desc "Create a Debug version of the app"
	lane :debug_app do
		bundle_rn
		test
		test_coverage
		inc_build_number
		build_app configuration:"Debug"
	end

	desc "Bundle RN for release"
	lane :bundle_rn do |lane|
		sh("cd ../.. && react-native bundle --dev false --platform ios --entry-file index.ios.js --bundle-output ./ios/main.jsbundle --assets-dest ./ios/HelloWorld")
	end

	desc "Runs all the tests"
	lane :test do
		scan(
			scheme: ENV["IOS_BUILD_SCHEME"],
			workspace: ENV["IOS_BUILD_WORKSPACE"],
			output_directory: "./build/reports"
		)
	end

	desc "Build the app"
	private_lane :build_app do |lane|
		configuration = "Release"

		if lane[:release] != true
			configuration = "Debug"
		end

		gym(
			scheme: ENV["IOS_BUILD_SCHEME"],
			workspace: ENV["IOS_BUILD_WORKSPACE"],
			configuration: configuration,
			output_directory: "./build/release",
			export_method: "ad-hoc",
			export_options: "./fastlane/ExportOptions.plist",
			export_xcargs: "-allowProvisioningUpdates"
		)
	end

	desc "Test coverage"
	lane :test_coverage do |lane|
		# Create Slather HTML report
		slather(
			html: true,
			output_directory: "./build/coverage/html"
		)
		# Create Slather Cobertura report
		slather
		# Convert Cobertura to Clover report
		sh("cobertura-clover-transform  ../build/coverage/cobertura.xml > ../build/coverage/clover.xml")
	end

	desc "Increment build number"
	lane :inc_build_number do |lane|
		if ENV['APP_BUILD_NUMBER_HelloWorld']
			increment_build_number(
	            build_number: ENV['APP_BUILD_NUMBER_HelloWorld']
	        )
		else
			increment_build_number(
	            build_number: "1"
	        )
		end
	end

	after_all do |lane|
		# Slack sucess message will be called from Bamboo! (comment left for reference)

		# This block is called, only if the executed lane was successful

		# slack(
		#   message: "Successfully deployed new App Update."
		# )
	end

	error do |lane, exception|
		# If something fails, trigger Slack message

		# slack(
		#   message: exception.message,
		#   success: false
		# )
	end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
