coverage_service: cobertura_xml
xcodeproj: AppPlatform.xcodeproj
scheme: AppPlatform
workspace: AppPlatform.xcworkspace
source_directory: ./AppPlatform
output_directory: ./build/coverage
ignore:
  - "AppPlatformTests/*"
