coverage_service: cobertura_xml
xcodeproj: HelloWorld.xcodeproj
scheme: HelloWorld
workspace: HelloWorld.xcworkspace
source_directory: ./HelloWorld
output_directory: ./build/coverage
ignore:
  - "HelloWorldTests/*"
